module.exports = [
  {
    name: 'Vue.js',
    value: 'vuejs',
    start: 'start',
    token: '9I0NMaGJZQaJQ4Qzmm5cHwtt',
    config: 'src/main.js',
    public: 'public',
    port: '3000',
  },
  {
    name: 'Nuxt.js V2 (Vue.js V2)',
    value: 'nuxtjs',
    start: 'dev',
    token: 'NKTXbnJKkSyy1rYi68dXyQtt',
    config: 'nuxt.config.js',
    public: 'static',
    port: '3000',
  },
  {
    name: 'Nuxt.js V3 (Vue.js V3)',
    value: 'nuxtjs-3',
    start: 'dev',
    token: 'NKTXbnJKkSyy1rYi68dXyQtt',
    config: 'nuxt.config.js',
    public: 'public',
    port: '3000',
  },
  {
    name: 'Next.js (React.js)',
    value: 'nextjs',
    start: 'dev',
    token: 'd6IKUtAUDiKyAhpJtrLFcwtt',
    config: 'pages/_app.js',
    public: 'public',
    port: '3000',
  },
  {
    name: 'React.js',
    value: 'reactjs',
    start: 'start',
    token: 'y0IMHyY6aWMwzWrTcVYz6wtt',
    config: 'src/index.js',
    public: 'public',
    port: '3000',
  },
  {
    name: 'Remix',
    value: 'remix',
    start: 'dev',
    token: 'd6IKUtAUDiKyAhpJtrLFcwtt',
    config: 'app/root.jsx',
    public: 'public',
    port: '3000',
  },
  {
    name: 'Svelte',
    value: 'sveltekit',
    start: 'dev',
    token: 'OurklwV5XsDJTIE1NJaD2wtt',
    config: 'src/routes/__layout.svelte',
    public: 'public',
    port: '3000',
  },
  {
    name: 'Gatsby.js (React)',
    value: 'gatsbyjs',
    start: 'start',
    token: 'd6IKUtAUDiKyAhpJtrLFcwtt',
    config: 'gatsby-config.js',
    public: 'static',
    port: '8000',
  },
]
